// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCredentials() {
  return window['go']['main']['App']['ClearCredentials']();
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportResults() {
  return window['go']['main']['App']['ExportResults']();
}

export function GetCurrentLogDir() {
  return window['go']['main']['App']['GetCurrentLogDir']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function HasCredentials() {
  return window['go']['main']['App']['HasCredentials']();
}

export function ImportServersFromCSV() {
  return window['go']['main']['App']['ImportServersFromCSV']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RunScheduleNow(arg1) {
  return window['go']['main']['App']['RunScheduleNow'](arg1);
}

export function SetCommands(arg1) {
  return window['go']['main']['App']['SetCommands'](arg1);
}

export function SetCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCredentials'](arg1, arg2, arg3);
}

export function SetServers(arg1) {
  return window['go']['main']['App']['SetServers'](arg1);
}

export function StartExecution(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartExecution'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['main']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateSchedule(arg1) {
  return window['go']['main']['App']['UpdateSchedule'](arg1);
}
