// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportResults() {
  return window['go']['main']['App']['ExportResults']();
}

export function GetCurrentLogDir() {
  return window['go']['main']['App']['GetCurrentLogDir']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function ImportServersFromCSV() {
  return window['go']['main']['App']['ImportServersFromCSV']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function PreviewCommands() {
  return window['go']['main']['App']['PreviewCommands']();
}

export function PreviewServers() {
  return window['go']['main']['App']['PreviewServers']();
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SelectCommandsFile() {
  return window['go']['main']['App']['SelectCommandsFile']();
}

export function SelectServersFile() {
  return window['go']['main']['App']['SelectServersFile']();
}

export function SetCommands(arg1) {
  return window['go']['main']['App']['SetCommands'](arg1);
}

export function SetServers(arg1) {
  return window['go']['main']['App']['SetServers'](arg1);
}

export function StartExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartExecution'](arg1, arg2, arg3);
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}
