// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentLogDir() {
  return window['go']['main']['App']['GetCurrentLogDir']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function PreviewCommands() {
  return window['go']['main']['App']['PreviewCommands']();
}

export function PreviewServers() {
  return window['go']['main']['App']['PreviewServers']();
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function SelectCommandsFile() {
  return window['go']['main']['App']['SelectCommandsFile']();
}

export function SelectServersFile() {
  return window['go']['main']['App']['SelectServersFile']();
}

export function StartExecution(arg1, arg2) {
  return window['go']['main']['App']['StartExecution'](arg1, arg2);
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}
