// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cisco} from '../models';

export function GetCurrentLogDir():Promise<string>;

export function GetLogFiles():Promise<Array<Record<string, string>>>;

export function IsRunning():Promise<boolean>;

export function OpenLogsFolder():Promise<void>;

export function PreviewCommands():Promise<Array<string>>;

export function PreviewServers():Promise<Array<cisco.Server>>;

export function ReadLogFile(arg1:string):Promise<string>;

export function SelectCommandsFile():Promise<string>;

export function SelectServersFile():Promise<string>;

export function StartExecution(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function StopExecution():Promise<void>;
